# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Documentation
site_url: https://minhnguyen1908.github.io/afe-fo-api

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.code.copy
    - content.code.annotate
    - toc.integrate

nav:
  - "Home": "index.md"
  - "1 Login|User Management":
      - "1.01 Login Request": "websocket/Login_UserManagement/1_login_request.md"
  - "2 Stock information":
      - "2.01 Stock information": "websocket/stock_information_request/stock_information_request.md"
  - "4 Back office related":
      - "4.01 Cash movement query": "websocket/4_back_office_related_request/01_cash_movement_query_request.md"
      - "4.02 Account transaction query": "websocket/4_back_office_related_request/02_account_transaction_query.md"
  - "Appendix": "websocket/appendix.md"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
